SHOW ENGINES;

CREATE TABLE table1(
id INT PRIMARY KEY,
name VARCHAR(20)
);

CREATE TABLE table2(
id INT PRIMARY KEY,
name VARCHAR(20)
) ENGINE=MyISAM;

SHOW TABLE STATUS;

ALTER TABLE table2 ENGINE=InnoDB;
ALTER TABLE table2 ADD COLUMN test char(10);
ALTER TABLE table2 MODIFY COLUMN test char(40);
ALTER TABLE table2 DROP COLUMN test;
